### ISSUE TITLE
problem with install on windows?

### ISSUE THREAD

**Issue by thearabbit** [zimme/meteor-bootstrap-hover-dropdown#1]
```
meteor add zimme:bootstrap-hover-dropdow
n
 => Errors while adding packages:

While downloading
zimme:bootstrap-hover-dropdown@2.1.3...:
error: connect ECONNREFUSED
```

**Comment by zimme** [comment]
From that error message I can see that it's a connection problem. For some reason your connection to the package download server was refused.

This isn't a problem with this package and I also believe it's a temporary problem.

If the problem persists I would open an issue at Meteor's issue tracker instead.

**Comment by thearabbit** [comment]
Now it work fine.

**Comment by zimme** [comment]
:+1:
