### ISSUE TITLE
Don't work?

### ISSUE THREAD

**Issue by thearabbit** [zimme/meteor-bootstrap-hover-dropdown#2]
I installed, and then testing.
But don't work, I use `bootstrap@3.3.4` (twbs:bootstrap).

**Comment by zimme** [comment]
You're gonna have to manually init the plugin for all the templates where you use it.

``` js
Template.menubar.rendered = function() {
  this.$('.dropdown-toggle').dropdownHover();
};
```

This will trigger the plugin for the template `menubar`

I'm gonna add some docs on this.
